AllCops:
  TargetRubyVersion: 2.7

  NewCops: enable

  Exclude:
    - 'bin/**'
    - 'db/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'node_modules/**/*'

Style/AndOr:
  EnforcedStyle: conditionals

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  CountComments: true

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  CountComments: true

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  CountComments: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - 'activestorage/db/migrate/**/*.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Max: 250
  Exclude:
    - "spec/**/*.rb"