version: "3.3"
networks:
  app:
    driver: bridge

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app

  web:
    build: .
    volumes:
      - .:/airbnb_clone
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app

volumes:
  postgres: