version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/airbnb_clone
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres: