version: "3.3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - internal_network

  web:
    build: .
    volumes:
      - .:/airbnb_clone
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - internal_network

volumes:
  postgres: