name: 'Terraform'

on:
  workflow_dispatch:
  
  push:
    branches:
    - main
    - master
    - terraform
        
  pull_request:
    branches:
    - main
    - master
        
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: write

jobs:

  Terraform-Apply:
    runs-on: ubuntu-latest
    name: Terraform
    environment: deploy
        
    defaults:
      run:
        shell: bash
          
    steps:
        
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
        terraform_wrapper: false
        
    - name: Terraform Init
      id: init
      run: terraform init
        
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -diff
      continue-on-error: true

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
        
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'push'
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Apply
      id: apply
      if: steps.plan.outcome == 'success' && github.event_name == 'push'
      run: terraform apply -auto-approve -no-color